### ISSUE TITLE
Add paper type

### ISSUE THREAD

**Issue by akerren** [Dev-Lan/vispubs#7]
Dear Devin,
As one of the current co-chairs of the STAR paper track of EuroVis, we are interested in to use your tool for showing all existing STAR papers to interested people but also future submitters. In the past, we had a manually curated list provided by Min Chen; but it would be better to use an existing tool like yours. Would it be possible to add a "paper types" category and here especially STAR reports?
Thanks and best, Andreas

**Comment by Dev-Lan** [comment]
Thanks for reaching out! I like the idea!

For my clarification, would this be adding a label to paper published at EuroVis that are already available on the VisPubs website? Or would it be adding additional papers and labeling them as STAR reports?

Either way, does some list of these papers already exist somewhere?

**Comment by akerren** [comment]
Hi Devin,

> On 24 Jun 2024, at 22:18, Devin Lange ***@***.***> wrote:
> 
> 
> Thanks for reaching out! I like the idea!
> For my clarification, would this be adding a label to paper published at EuroVis that are already available on the VisPubs website? Or would it be adding additional papers and labeling them as STAR reports?

I think that all STAR should be already somewhere on the VisPubs website. I guess you still have to add the papers from EuroVis 2024 (seems not to be added yet)? 

For some reasons, I cannot find the STARs for EuroVis 2023, but they should be there? For instance, the STAR “The State of the Art in Visualizing Dynamic Multivariate Networks” is not there I think. 

Thus, I believe my answer is yes to both of your questions. :-/

Another complexity are CGF surveys that are presented in EuroVis Star sessions (invited papers), but I think we can ignore those here. 

> Either way, does some list of these papers already exist somewhere?

There was an old list in the web somewhere, which disappeared. So, I do not think so. :-(

Thanks and best,

Andreas


> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

-- 

+-------------------------------------------------------
+ Prof. Dr. Andreas Kerren
+
+ Linnaeus University
+ Department of Computer Science and Media Technology
+ Vejdes Plats 7
+ SE-351 95 Växjö, Sweden
+
+ Phone: +46 470 767502
+ Fax: +46 470 84004
+ Email: ***@***.***
+ WWW: https://bit.ly/akerren-liu
+ WWW: http://cs.lnu.se/isovis/
+-------------------------------------------------------

**Comment by Dev-Lan** [comment]
Ah good catch! For 2023 I added papers directly from the [Eurographics site.](https://diglib.eg.org/collections/f85665f0-5201-4ce0-a1a9-afcc5a38d956) For earlier papers I got the list from dblp. It seems that dblp includes the STAR papers, but eg does not.

One possible solution is to use the existing search/filter feature. E.g. [this link](https://vispubs.com/?filterPanelOpen=true&venueFilter=EuroVis&searchText=state+of+the+art|state-of-the-art&useRegex=true) includes all papers from EuroVis that include "state of the art" or "state-of-the-art" in the title or abstract. Probably not perfect, but it works today.

>  I guess you still have to add the papers from EuroVis 2024 (seems not to be added yet)?

Yes, I'm working on updating the data ingestion to make it more streamlined. Unfortunately, this update will require the papers to be on dblp which has some delay. EuroVis 2024, is not listed on dblp yet.

**Comment by Dev-Lan** [comment]
Anyway, it seems the missing papers are just mistakes on my end that will be fixed. I'm not sure how well a paper type would fit more broadly into the dataset. For instance should VIS survey papers be labeled as STARs? What other paper types would there be?

One alternative to a paper type that could fit this is to have collections? E.g. a "EuroVis STARs" that filters to a defined list of papers. Not sure if there are other collections that would be useful, but this avoids the issue of how to label the paper types for all the other papers.

**Comment by akerren** [comment]
> On 25 Jun 2024, at 19:55, Devin Lange ***@***.***> wrote:
> 
> 
> Anyway, it seems the missing papers are just mistakes on my end that will be fixed. I'm not sure how well a paper type would fit more broadly into the dataset. For instance should VIS survey papers be labeled as STARs? What other paper types would there be?

There are not many VIS survey papers. A STAR is always related to EuroVis or Eurographics. 

> One alternative to a paper type that could fit this is to have collections? E.g. a "EuroVis STARs" that filters to a defined list of papers. Not sure if there are other collections that would be useful, but this avoids the issue of how to label the paper types for all the other papers.

A collection would be also fine for us I guess!

Thanks and best,

Andreas


> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

-- 

+-------------------------------------------------------
+ Prof. Dr. Andreas Kerren
+
+ Linnaeus University
+ Department of Computer Science and Media Technology
+ Vejdes Plats 7
+ SE-351 95 Växjö, Sweden
+
+ Phone: +46 470 767502
+ Fax: +46 470 84004
+ Email: ***@***.***
+ WWW: https://bit.ly/akerren-liu
+ WWW: http://cs.lnu.se/isovis/
+-------------------------------------------------------

**Comment by Dev-Lan** [comment]
@akerren — I finally got around to this request :)

I have marked the issue as completed since the functionality for collections has been added to the website. In addition, I have created an initial collection for EuroVis STARs, though I have limited this to 2024 and 2023. This collection can be accessed from the bottom of the filter panel. It can also be accessed directly from this URL:
https://vispubs.com/?collection=EuroVisSTAR

What I would like to request is that the EuroVis committee complete the information for this collection. This can be done by submitting a PR with the updated information in this file:
https://github.com/Dev-Lan/vispubs/blob/main/public/data/collections/EuroVisSTAR.json

No need to functionally test your changes, I will do that before I merge them.

The title and description appear at the bottom of the filter panel:
<img width="299" alt="Screenshot 2024-09-15 at 5 54 50 PM" src="https://github.com/user-attachments/assets/3e29b208-60ee-4900-8870-9224b003dace">

The papers list expects the list of DOIs in the collection. I've added STAR papers from 2024/2023 (not including invited talks from CG&A or TVCG). The order of the DOIs does not matter.

On the note of invited talks, I would like to add papers from CG&A, TVCG and CGF in the future. So feel free to add STAR papers that are invited talks to the JSON. Extra DOIs will not cause problems, but they will be noted as not appearing on the website (see the screenshot for how this would look if 3 extra papers were included). The advantage to adding them now is that if I add the papers later, they will automatically be included in the collection.

Feel free to reach out here or email if you have any suggestions or feedback!

**Comment by akerren** [comment]
PR#15 <https://github.com/Dev-Lan/vispubs/pull/15> adds the STARs published in EG digital library (2015-2022).

Regarding invited talks: I will see whether we can dig this up, but it's is going to take a bit longer due to having to go through the programs of past EuroVis’s by hand. It would also change the purpose of the collection from "papers published in the EuroVis STAR track” to “surveys or similar presented at EuroVis”. I think we (STAR chairs) want the former, but the latter may be more useful to everyone.

Lastly: We are about to send out our CFP (Sep 23). It would be great if we could include a link to the STARs collection. Does your timeline allow for that? 

Thanks & Best
Christoph

**Comment by Dev-Lan** [comment]
> I think we (STAR chairs) want the former, but the latter may be more useful to everyone.
- I'm happy for this collection to be whichever you prefer. Let's leave this one as "EuroVis STAR track" papers. 

> Does your timeline allow for that? (Sep 23)
- Yes this should be easy. I'll take a look at the PR today (Sep 16), if everything is good it should be live by tomorrow.

**Comment by Dev-Lan** [comment]
Quick update + question.

First, I've merged your changes, so this link now includes all the STAR papers from 2016-2024: https://vispubs.com/?collection=EuroVisSTAR

My question has to do with the STAR papers from 2014–2015. My interpretation from looking through the eurographics and dblp website is that for the first two years, the STAR papers were published in a separate track as a conference/workshop paper and were not included in CGF with the other EuroVis papers. Then in 2016, this changed and they were included in CGF.

So my question is if this is a correct interpretation? Currently, the STAR papers from 2014-2015 are not on the vispubs website since I was pulling from the CGF, but I could consider adding the STAR papers for these two years.
